name: Changeset

on:
  push:
    branches: [main]

jobs:
  create-release-pr:
    name: Create Changeset PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - name: Create Release Pull Request
      uses: changesets/action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
